/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package main.solver;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import io.github.bonigarcia.wdm.WebDriverManager;

public class Library {
    public static void main(String[] args) {
    	WebDriver webDriver = getWebDriver();
    	
    	new MineSweeperSolver(webDriver);
    }
    
    private static WebDriver getWebDriver() {
    	WebDriverManager.chromedriver().setup();
    	
    	return new ChromeDriver();
    }
}
